### ISSUE TITLE
PALETTE: C&C 6bit .pal import produces incorrect colors

### ISSUE THREAD

**Issue by Metadorius** [vengi-voxel/vengi#519] opened 2024-09-15 13:22 UTC
When I convert to PNG with my script:

![image](https://github.com/user-attachments/assets/08136cd0-7765-4f3f-bd7c-f5cc220e8304)

When I open the pal directly:

![image](https://github.com/user-attachments/assets/b56cdf0b-4cd4-4002-a52a-6604d9313e29)

**Comment by Metadorius** [comment] 2024-09-15 13:24
```py
import png
import struct


fname = input("*.pal to convert: ")


with open(fname, "rb") as pal:
    data = pal.read(768)
    palette = list(struct.unpack("768B", data))
    palette = (palette, )

with open(fname + ".png", "wb") as pngpal:
    w = png.Writer(width=256, height=1, bitdepth=6, greyscale=False)
    w.write(pngpal, palette)
```

Here's the conversion script in Python, requires `pypng`.

**Comment by mgerhardy** [comment] 2024-09-15 13:25
For my future me ;): This is a C&C `pal` file.

Can you maybe please attach the pal file for testing purposes?

**Comment by Metadorius** [comment] 2024-09-15 13:26
Sure thing.
[unitsno.zip](https://github.com/user-attachments/files/17005894/unitsno.zip)

Also here's the reference to the format:
https://modenc.renegadeprojects.com/PAL

**Comment by mgerhardy** [comment] 2024-09-15 13:40
Thanks a lot - the reading is fixed now by trying to identify whether the pal file is 6 bit only. The problem here is that the pal file is not only used by C&C as 6 bit value - but also by other tools/games that are using 8 bit values.

The issue is not yet resolved for writing.

This is most likely becoming a cvar to control the behavior and to let it work for both cases.

**Comment by Metadorius** [comment] 2024-09-15 13:50
How about an option/toggle for specifying bit depth? Or perhaps having multiple .pal formats to choose from?

**Comment by mgerhardy** [comment] 2024-09-15 13:52
![Bildschirmfoto vom 2024-09-15 15-51-29](https://github.com/user-attachments/assets/e5f379f9-4d3d-40ba-96a5-7024cc7c5794)

this is the case now - if you select the RGB Palette (*.pal) in the file filter list, you get this option

**Comment by mgerhardy** [comment] 2024-09-15 13:54
![Bildschirmfoto vom 2024-09-15 15-54-34](https://github.com/user-attachments/assets/b1113a95-8010-4c7c-856d-9c309a5bf925)

this is with the 6 bit option activated

**Comment by Metadorius** [comment] 2024-09-15 17:31
Can confirm the option works. I think the name would not be intuitive to C&C users though, as they don't have an idea what is 6-bit colors. Perhaps the best thing to do would be to have it as a separate file format, as you already do with JASC palette? Then if the user selected the pal file - ask which of the formats is this file in when opening/saving (if all formats are selected for filtering the view).

**Comment by mgerhardy** [comment] 2024-10-22 18:06
see #536 - the idea could also be to load the 6bit colors in the c&c view mode

**Closed** 2024-10-22 18:56 UTC
Labels: format
